const SKILLS_DESKTOP_BREAKPOINT_PX = 1024;

export const SKILLS_DESKTOP_MEDIA_QUERY = `(min-width: ${SKILLS_DESKTOP_BREAKPOINT_PX}px)`;
export const SKILLS_MOBILE_MEDIA_QUERY = `(max-width: ${SKILLS_DESKTOP_BREAKPOINT_PX - 1}px)`;
