import { type PlaywrightTitle, playwrightTitleRecords } from '../helpers';
import { defineParityShard } from '../schema';

const owner = 'X0' as const;
const inFile = (file: string, titles: readonly string[]): readonly PlaywrightTitle[] =>
  titles.map((title) => ({ file: `apps/web/e2e/${file}`, title }));

const titles = [
  ...inFile('accessibility.spec.ts', [
    'Usage report exposes shared navigation without narrow overflow',
    'Skill management exposes shared navigation without narrow overflow',
    'Sources exposes shared navigation without narrow overflow',
    'Sync exposes shared navigation without narrow overflow',
    'keeps the active report destination visible after deep scrolling',
    'draws contrasting timeline and dashboard-panel focus indicators in light mode',
    'draws contrasting timeline and dashboard-panel focus indicators in dark mode',
    'reduced motion keeps drawer feedback while making motion effectively immediate',
    'Overview has no detectable accessibility violations',
    'the open session drawer has no detectable accessibility violations',
    'Skills has no detectable accessibility violations',
    'Sources has no detectable accessibility violations',
    'Sync has no detectable accessibility violations',
  ]),
  ...inFile('audit-performance.spec.ts', ['records deterministic bounded DOM measurements for the audit']),
  ...inFile('campaign-label-overrides.spec.ts', [
    'renames and resets one page-local campaign label without changing its filter key',
  ]),
  ...inFile('category-visibility.spec.ts', [
    'keeps every populated harness and machine visible with default dimension filters',
  ]),
  ...inFile('dashboard-presentation.spec.ts', [
    'groups value bases while keeping the remaining metric deltas qualified and aligned',
    'keeps metric provenance visibly interactive and operable by keyboard',
    'explains unavailable source freshness without replacing its compact pill',
    'keeps spend coverage textual without an Overview segmented bar',
    'renders Token anatomy as four exact definition rows without a segmented bar',
    'renders secondary status only on Overview and puts Projects before closed group management',
    'uses one fixed-size Punchcard intensity channel with a low/high key',
    'separates timeline boundary dates and retains no horizontally intersecting tick',
    'keeps the mobile filter stack coherent with content above the fold',
  ]),
  ...inFile('dashboard.spec.ts', [
    'loads a deterministic report overview',
    'locks definitive output while a focused filter response is pending',
    'retries a failed report through the Router loading lifecycle',
    'uses one primary navigation while preserving Breakdown deep links and sub-tabs',
    'copies the exact breakdown URL and exports only visible sorted model rows',
    'shows analysis and report metrics without disclosure gates',
    'prioritizes the selected dashboard view before secondary status on mobile',
    'keeps the selected dashboard view ahead of secondary provider status on desktop',
    'keeps provider details collapsed until they are requested',
    'Codex quota history shows reset and gap-aware ranges on desktop and mobile',
    'persists exploration state in the URL',
    'shows the text query as a directly removable active filter',
    'updates the date range and opens a session drawer',
    'opens a session from Overview without leaving the current analysis',
    'navigates and closes the selected session with drawer keyboard commands',
    'starts sessions with focused work columns and switches metric presets',
    'renders a human campaign root as not a subagent',
    'uses the report range as the only graph viewport',
    'offers keyboard-safe charts and mobile summaries at a narrow viewport',
    'keeps compact heatmap geometry at narrow and desktop viewports',
    'selects the same heatmap day with mouse and keyboard',
    'mounts one Sessions surface across viewport changes without losing state',
    'keeps sync limited to explicit file transfers',
  ]),
  ...inFile('drawer-value-presentation.spec.ts', ['uses one token magnitude and accessible drawer explanations']),
  ...inFile('machine-staleness.spec.ts', [
    'surfaces a stale machine outside sync while preserving its raw filter value',
  ]),
  ...inFile('origin-campaign.spec.ts', [
    'makes the neutral origin default and singleton campaigns explicit',
    'ignores legacy campaign opt-out URLs and keeps every top-level row bounded and campaign-shaped',
  ]),
  ...inFile('origin-gap.spec.ts', ['renders undeclared origin outside the stack with its three causes']),
  ...inFile('session-viewport-geometry.spec.ts', [
    'anchors the virtual Session viewport inside the screen on desktop and mobile',
  ]),
  ...inFile('skills.spec.ts', [
    'opens a managed SKILL.md as an immediately editable document and saves with the pointer',
    'saves with Control+S and Meta+S while accepting immediate follow-up edits',
    'wraps long SKILL.md prose without changing the source value',
    'preserves the exact local draft when SKILL.md changed on disk',
    'preserves the exact local draft after another save failure',
    'saves SKILL.md source without installing it into runtimes',
    'protects an unsaved SKILL.md draft during navigation and reload',
    'refreshes the skills snapshot and inventories without silently replacing a draft',
    'preserves a source repository draft across an unrelated snapshot refresh',
    'keeps every Skills mutation inside the deterministic E2E backend',
    'shows the document inspector with actions in a single place',
    'keeps the tree, editor, and Inspector in one bounded desktop workspace row',
    'bounds long scope labels and makes validation findings individually identifiable',
    'presents unmanaged copies as neutral backlog rows with their reconciliation action',
    'prioritizes the editor on mobile and keeps the compact picker behavior',
    'renders matrix cards on mobile and preserves the desktop comparison table',
  ]),
  ...inFile('sources.spec.ts', [
    'states each source health once and keeps source metadata concise',
    'keeps business sources independent through a picked disable and publishes once',
    'ignores a partial SSE snapshot after a complete catalogue',
    'renders only deviation cards beside the healthy-source summary',
    'renders count-free source progress without assigning a non-finite native value',
  ]),
  ...inFile('theme.spec.ts', [
    'resolves the initial light theme before naming the toggle',
    'resolves the initial dark theme before naming the toggle',
  ]),
  ...inFile('time-range.spec.ts', [
    'uses one report range for the dashboard and activity chart',
    'uses clickable heatmap days as Rhythm activity-day controls without a native date input',
    'filters the report from non-empty Punchcard cells with click and keyboard',
    'changes every chart option from its segmented controls',
    'groups the timeline by campaign, machine, and origin with matching legends',
    'commits preset, text, keyboard, and pointer report ranges to the URL',
    'does not capture wheel scrolling over the activity chart',
    'keeps the report range canonical across granularity and domain changes',
  ]),
  ...inFile('value-presentation.spec.ts', ['renders measured, partially measured, and zero Breakdown bars distinctly']),
  ...inFile('visual-regression.spec.ts', [
    'matches the desktop Overview',
    'matches Overview with an open session drawer',
    'matches the narrow Overview value proposition',
    'matches the hydrated Skills workspace',
  ]),
  ...inFile('demo-privacy.spec.ts', ['serves only the synthetic report and keeps every local boundary inert']),
  ...inFile('production-report.spec.ts', [
    'renders the report timeline on the initial production Overview',
    'provides one accessible responsive source-control surface',
    'keeps the Report range mounted while focused chart options refresh',
    'keeps the last complete report visible while the report range changes',
    'hydrates and automatically pages Sessions through the production revision protocol',
    'opens Claude chronology and recorded source control from the production revision',
    'automatically pages mobile Sessions while scrolling',
  ]),
  ...inFile('session-scroll.scale.ts', [
    'reaches every top-level production campaign exactly once on desktop',
    'reaches every top-level production campaign exactly once on mobile',
  ]),
  ...inFile('session-scroll-benchmark.scale.ts', [
    'warms the production fixture without recording a sample',
    'records production sample 1',
    'records production sample 2',
    'records production sample 3',
  ]),
] as const;

export default defineParityShard({
  owner,
  records: playwrightTitleRecords(owner, titles),
});
