import type { ComponentProps } from 'svelte';
import type CampaignLabelEditor from '../actions/campaign-label-editor.svelte';
import type ProjectGroupEditor from '../actions/project-group-editor.svelte';
import type QuotaHistoryOwner from '../actions/quota-history-owner.svelte';
import type QuotaHistoryPanel from '../actions/quota-history-panel.svelte';
import type ReportSharingActions from '../actions/report-sharing-actions.svelte';
import type ActiveFilters from './active-filters.svelte';
import type BreakdownPanel from './breakdown-panel.svelte';
import type BreakdownRow from './breakdown-row.svelte';
import type CursorAttributionPanel from './cursor-attribution-panel.svelte';
import type DashboardBreakdown from './dashboard-breakdown.svelte';
import type FilterBar from './filter-bar.svelte';
import type HarnessProviderPanel from './harness-provider-panel.svelte';
import type OriginFilter from './origin-filter.svelte';
import type ProjectSummary from './project-summary.svelte';
import type ProjectsPanel from './projects-panel.svelte';

export type ActiveFiltersProps = ComponentProps<typeof ActiveFilters>;
export type BreakdownPanelProps = ComponentProps<typeof BreakdownPanel>;
export type BreakdownRowProps = ComponentProps<typeof BreakdownRow>;
export type CampaignLabelEditorProps = ComponentProps<typeof CampaignLabelEditor>;
export type CursorAttributionPanelProps = ComponentProps<typeof CursorAttributionPanel>;
export type DashboardBreakdownProps = ComponentProps<typeof DashboardBreakdown>;
export type FilterBarProps = ComponentProps<typeof FilterBar>;
export type HarnessProviderPanelProps = ComponentProps<typeof HarnessProviderPanel>;
export type OriginFilterProps = ComponentProps<typeof OriginFilter>;
export type ProjectGroupEditorProps = ComponentProps<typeof ProjectGroupEditor>;
export type ProjectSummaryProps = ComponentProps<typeof ProjectSummary>;
export type ProjectsPanelProps = ComponentProps<typeof ProjectsPanel>;
export type QuotaHistoryOwnerProps = ComponentProps<typeof QuotaHistoryOwner>;
export type QuotaHistoryPanelProps = ComponentProps<typeof QuotaHistoryPanel>;
export type ReportSharingActionsProps = ComponentProps<typeof ReportSharingActions>;
